/*

 ASTEROID_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __asteroid_tiles_h_INCLUDE
#define __asteroid_tiles_h_INCLUDE

/* Bank of tiles. */
#define asteroid_tilesBank 0
/* Start of tile array. */
extern const unsigned char asteroid_tiles[];

#endif

/* End of ASTEROID_TILES.H */
