/*

 BCKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : space1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bckground_h_INCLUDE
#define __bckground_h_INCLUDE

#define bckground_mapWidth 32
#define bckground_mapHeight 32
#define bckground_mapBank 0

extern const unsigned char bckground_map[];

#endif

/* End of BCKGROUND.H */
