/*

 GAMEOVER_SCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 31 x 32
   Tile set      : space1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __gameover_screen_h_INCLUDE
#define __gameover_screen_h_INCLUDE

#define gameover_mapWidth 31
#define gameover_mapHeight 32
#define gameover_mapBank 0

extern const unsigned char gameover_map[];

#endif

/* End of GAMEOVER_SCREEN.H */
