/*

 SENSOR_SCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 31 x 32
   Tile set      : sensor_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __sensor_screen_h_INCLUDE
#define __sensor_screen_h_INCLUDE

#define sensor_screenWidth 31
#define sensor_screenHeight 32
#define sensor_screenBank 0

extern const unsigned char sensor_screen[];

#endif

/* End of SENSOR_SCREEN.H */
