/*

 WINDOW.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 31 x 32
   Tile set      : window_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __window_h_INCLUDE
#define __window_h_INCLUDE

#define window_mapWidth 31
#define window_mapHeight 32
#define window_mapBank 0

extern const unsigned char window_map[];

#endif

/* End of WINDOW.H */
